version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:2.7.18
    steps:
       - checkout
       - run:
           command: |
             pip install --user sqlalchemy
             pip install --user python-dateutil
             python setup.py install --user
       - persist_to_workspace:
           root: ~/.local
           paths:
             - lib # Save installed Python libraries (including dbp itself)
  unittest:
    docker:
      - image: circleci/python:2.7.18
    steps:
       - checkout
       - attach_workspace:
           at: ~/.local
       - run:
           command: |
             python unit_tests/test_all.py -v
  createpostgres:
    docker:
      - image: circleci/python:2.7.18
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: circle_test
      POSTGRES_PASSWORD: ""
      PGPORT: 5432
      PGUSER: root
      PGDATABASE: sndd
      PGPASSWORD: ""
      PGHOST: localhost
    steps:
       - checkout
       - attach_workspace:
           at: ~/.local
       - run:
           command: |
             sudo apt install -y postgresql-client
             createdb -h localhost sndd -O root
             pip install --user psycopg2
             python scripts/CreateDBsabrs.py

workflows:
  main:
    jobs:
     - build
     - unittest:
         requires:
           - build
     - createpostgres:
         requires:
           - build
