version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:2.7.18
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
       - checkout
       - run:
           command: |
             pip install --user sqlalchemy
             pip install --user python-dateutil
             python setup.py install --user
       - persist_to_workspace:
           root: ~/.local
           paths:
             - lib # Save installed Python libraries (including dbp itself)
  unittest:
    docker:
      - image: circleci/python:2.7.18
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
       - checkout
       - attach_workspace:
           at: ~/.local
       - run:
           command: |
             python unit_tests/test_all.py -v
  createpostgres:
    docker:
      - image: circleci/python:2.7.18
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: circle_test
      POSTGRES_PASSWORD: ""
      PGPORT: 5432
      PGUSER: root
      PGDATABASE: sndd
      PGPASSWORD: ""
      PGHOST: localhost
    steps:
       - checkout
       - attach_workspace:
           at: ~/.local
       - run:
           command: |
             sudo apt update
             sudo apt install -y postgresql-client
             createdb -h localhost sndd -O root
             pip install --user psycopg2
             python scripts/CreateDBsabrs.py
  docs:
    docker:
      - image: circleci/python:2.7.18
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
       - checkout
       - attach_workspace:
           at: ~/.local
       - run:
           command: |
             rm -f ./setup.cfg # So sphinx-build doesn't go in ~/dbUtils
             pip install --user sphinx numpy
             pip install --user numpydoc
             make -C sphinx html | tee doc_output.txt
             # Fail (return nonzero) if there are warnings in output.
             ! grep -e "^build succeeded.*warning.*$" < doc_output.txt

workflows:
  main:
    jobs:
     - build
     - unittest:
         requires:
           - build
     - createpostgres:
         requires:
           - build
     - docs:
         requires:
           - build
