version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:2.7.18
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: sndd
    environment:
    steps:
       - checkout
       - run: sudo chown -R circleci:circleci /usr/local/bin
       - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
       - run:
         command: |
           sudo apt install -y postgresql-client
           createdb -h localhost sndd_test -O user
           createdb -h localhost sndd_special -O user
           pip install sqlalchemy

workflows:
  main:
    jobs:
     - build
