version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:2.7.18
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    
      - image: circleci/postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: circle_test
      POSTGRES_PASSWORD: ""
      PGPORT=5432
      PGUSER=root
      PGDATABASE=sndd
      PGPASSWORD=""
      PGHOST=localhost
    steps:
       - checkout
       - run: sudo chown -R circleci:circleci /usr/local/bin
       - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
       - run: 
           command: |
             sudo apt install -y postgresql-client
             createdb -h localhost sndd -O root
             pip install sqlalchemy
             pip install python-dateutil
             pip install psycopg2
             apt-get install vi
             python setup.py install
             python scripts/CreateDBsabrs.py

workflows:
  main:
    jobs:
     - build
